name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.12.6'
      - run: python --version
      - run : uname -a
      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install -U pytest
          pip install -r requirements.txt
          pip install -r requirements.text.txt
      - run: pytest